import Head from 'next/head';
import Hero from '../components/hero';
import Slide from '../components/slide';
import {slidedata} from '../components/slidedata'
import Instagram from '@/components/instagram';

import Stake from '../components/stakingapp'
import SignUp from '../components/signup'
import Home3 from '../components/home'
import Footer from '../components/footer'

function Home() {
  return (
    <div>
     
    <Head>
      <title>Amena Next App</title>
      <meta name='description' content='Generated by creat next app'/>
      <link rel='icon' href='/favicon.ico'/>
      
    </Head>
    
    {/*<Hero heading='Capture Photography' message='I capture moments in nature'/>
    <Slide slides={slidedata}/>
  <Instagram/>
  <Login/>*/}
  
  {/* <Login/> */}
  {/* <Stake/> */}
  {/* <SignUp/>     */}
  {/* <Home3/>
  <Footer/> */}
    </div>

    );
}
export default Home;